### ISSUE TITLE
The Comment Syntax is wrong 

### ISSUE THREAD

**Issue by daslicht** [whatwedo/vscode-twig#1]
Hi,
The Comment Syntax is wrong.
Currently if you add a comment by using ```cmd + / ``` adds a html comment: 
```<!-- -->```
The correct Twig Comment Syntax is however : 
```{# #}```

**Comment by renestalder** [comment]
Thanks for reporting. 

I'm not able working on the fix in the next 3 weeks so I'm glad for any pull request on this.

**Comment by daslicht** [comment]
Alright, I created a Pull Request

**Comment by renestalder** [comment]
Thank you Marc. Will publish it later to the vsco extension platform.

**Comment by daslicht** [comment]
Thank you !

**Comment by renestalder** [comment]
Your changes are now in the marketplace in version v1.0.1.

**Comment by daslicht** [comment]
nice,
another thing I have noticed is that when you highlight a div , its opening or closing tag is not highlighted. Instead, all divs are highlighted :/

**Comment by renestalder** [comment]
Can you open another Issue and attaching a screenshot? I will look into it. 

Thanks for posting this issues back to Github. I appreciate that.

**Comment by mcclaskiem** [comment]
I am still getting this error only it is trying to us JS/CSS syntax when using `CMD + /`

![screen shot 2016-12-19 at 9 37 12 am](https://cloud.githubusercontent.com/assets/6970287/21316443/c4f43aee-c5ce-11e6-9960-808c41d6f5b2.png)

I highlight the line and then use the key command for comment and this it what it outputs.

**Comment by renestalder** [comment]
@mcclaskiem Well, this is a different problem. Technically, there isn't a single line comment in Twig, but we forget to remove this from the converted Text Mate package. So you fix this issue with using the shortcut for block comments.

We will remove the single line comment from the syntax to make this more clear.

**Comment by mcclaskiem** [comment]
I am getting the same issue on a block as well.

![screen shot 2016-12-19 at 10 10 40 am](https://cloud.githubusercontent.com/assets/6970287/21317519/729ac1dc-c5d3-11e6-9d19-56758d3349f9.png)

**Comment by renestalder** [comment]
v1.0.2 is out now. Update your extensions. You'll see, the removed single line comment function will fallback to the block comment function, thus making it work as you expect.

**Comment by mcclaskiem** [comment]
Thank you! Works perfectly
