### ISSUE TITLE
Just use for htm files not html ?

### ISSUE THREAD

**Issue by daslicht** [whatwedo/vscode-twig#7]
Hi,
how do you just enable this package for ```htm``` and not ```html``` files.

Or is there a way to disable the Plugin for a certain Project ?

The thing is , when developing non twig based things, we still get the comment syntax of twig 

```{# #}```

 which is a kind of disturbing.

**Comment by renestalder** [comment]
Per definition in the syntax, it should only automatically apply to .twig and html.twig files. How can I test your scenario?

**Comment by daslicht** [comment]
Hi, it also applies to *.html / *.htm files

**Comment by daslicht** [comment]
And there is no way to assign a certain file type to an extension :
eg: 
*.twig, *.htm = ===  >use twig 
*.html just use html

**Comment by renestalder** [comment]
Well, this never happened in our test, neither I can verify by creating just an empty HTML file and use the comment shortcut. It makes an html comment, doesn't matter if I use .htm or .html extension.

- Can you elaborate with more details so I can build a test scenario?
- What other extension do you have installed?
- When you create a new HTML file, what syntax does Visual Studio Code choose by default (see lower right part of the UI).

![screen shot 2016-11-02 at 12 15 02](https://cloud.githubusercontent.com/assets/105358/19926689/382ddb1c-a0f6-11e6-9bc2-7353dea18485.png)

**Comment by renestalder** [comment]
> And there is no way to assign a certain file type to an extension

There is, and it is possible you already did. Use the command palette and choose **Change Language Mode**.

![bhodfloljx](https://cloud.githubusercontent.com/assets/105358/19926765/c1d6e2d2-a0f6-11e6-9317-360daad230eb.gif)

**Comment by daslicht** [comment]
I am talking about this extension : ```TWIG pack``` by Bajdzis he refered to your repo, lol
Looks like he messed sometging up.

I use you Plugin now...

**Comment by renestalder** [comment]
Well, he "dirty" copied our code and also made changes to it. So It's quite possible he has other bugs in his extension than we have.

**Comment by daslicht** [comment]
see : https://github.com/whatwedo/vscode-twig/compare/master...daslicht:patch-1

**Comment by renestalder** [comment]
Not quite sure what this pull request have to do with your problem. It just removes the (false, yes), single line comment. Would btw. be better to replace it with the twig syntax, which is the same for multiline and single line comments.

> The thing is , when developing non twig based things, we still get the comment syntax of twig
> {# #}

**Comment by gmhcode** [comment]
go to settings, in "files.associations" add "files.associations": { "*.html": "html" }
